import {createGame} from '../game/src/main.js';
import {CITIES,pointAt,ROADS} from '../game/src/data.js';
import {fresh} from '../game/src/model.js';
const params=new URLSearchParams(location.search),scene=params.get('scene');
if(scene){const d=fresh(),city=Number(params.get('city')??0),c=CITIES[city],hour=Number(params.get('hour')??15.3);d.hour=hour;d.weather=params.get('weather')??'clear';d.settings.weather=d.weather;d.settings.quality=params.get('quality')??'high';d.settings.sound=false;
 if(scene==='compare'){d.truck.x=c.x+92.1586;d.truck.z=c.z-.6581;d.truck.yaw=1.742;d.truck.fuel=183;d.active={id:'qa-food',from:city,to:Math.min(9,city+1),cargo:'food',stage:'loaded',pay:13200,limit:385,elapsed:25,damage:0,startDamage:0,detached:false};d.target=d.active.to;d.trailer={x:d.truck.x-Math.sin(d.truck.yaw)*9.9,z:d.truck.z-Math.cos(d.truck.yaw)*9.9,yaw:d.truck.yaw};}
 if(scene==='road'){const road=ROADS[Math.min(8,city)],p=pointAt(road,road.length*.45,-3);Object.assign(d.truck,p,{yaw:p.heading});d.target=Math.min(9,city+1);}
 if(scene==='landmark'){d.truck.x=c.x+80;d.truck.z=c.z-65;d.truck.yaw=Math.PI*.78;d.target=city;}
 localStorage.setItem('volga-haul-progress-v1',JSON.stringify(d));}
createGame().then(async g=>{window.__qaGame=g;window.__qaStage=async({city=0,scene='landmark',hour=15.3,weather='clear',cam=2})=>{const c=CITIES[city],d=g.model.data;g.physics.removeTrailer();d.active=null;d.trailer=null;d.hour=hour;d.weather=weather;d.settings.weather=weather;d.target=city;g.model.speed=0;if(scene==='compare'){Object.assign(d.truck,{x:c.x+92.1586,z:c.z-.6581,yaw:1.742});d.active={id:'qa-food',from:city,to:Math.min(9,city+1),cargo:'food',stage:'loaded',pay:13200,limit:385,elapsed:25,damage:0,startDamage:0,detached:false};d.trailer={x:d.truck.x-Math.sin(d.truck.yaw)*9.9,z:d.truck.z-Math.cos(d.truck.yaw)*9.9,yaw:d.truck.yaw};}else if(scene==='road'){const r=ROADS[Math.min(8,city)],p=pointAt(r,r.length*.45,-3);Object.assign(d.truck,p,{yaw:p.heading});d.target=Math.min(9,city+1);}else Object.assign(d.truck,{x:c.x+80,z:c.z-65,yaw:Math.PI*.78});g.physics.teleport();g.view.mode=cam;g.view.cameraReady=false;await g.action('resume');g.ui.update(null,g.physics);return {city:c.en,scene,hour,weather,cam};};if(scene){g.view.mode=Number(params.get('cam')??2);g.view.cameraReady=false;await g.action('resume');}}).catch(error=>console.error(error));
